name: Run Tests and Create PR

on:
  push:
    branches:
      - '**'  # Qualquer branch

jobs:
  test-and-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run tests and generate Jacoco report
        run: mvn clean test jacoco:report

      - name: Extract coverage from HTML report
        run: |
          FILE="target/site/jacoco/index.html"
          if [ -f "$FILE" ]; then
            # Extrai a linha do <tfoot> com "Total"
            LINE=$(grep -oP '(?s)(?<=<tfoot>).*?(?=</tfoot>)' "$FILE" | grep '<td>Total</td>')
            # Extrai o conteúdo da terceira <td> (índice 2) que contém a cobertura (ex: 93%)
            COVERAGE=$(echo "$LINE" | grep -oP '(?<=<td[^>]*>)[0-9]{1,3}%')
            # Pega apenas o terceiro valor encontrado (a terceira td)
            COVERAGE=$(echo "$COVERAGE" | sed -n 3p)
            echo "✅ Cobertura total: $COVERAGE"
          else
            echo "❌ Arquivo de cobertura não encontrado: $FILE"
            exit 1
          fi

  create-pr-to-develop:
    needs: test-and-report
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create pull request to develop
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: develop
          branch: ${{ github.ref_name }}
          title: "Auto PR: Merge '${{ github.ref_name }}' into develop"
          body: |
            Este PR foi criado automaticamente após o build e testes com Jacoco.
          draft: false
          labels: automated-pr
