name: Run Tests and Create PR

on:
  push:
    branches:
      - '**'  # Qualquer branch

jobs:
  test-and-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run tests and generate Jacoco report
        run: mvn clean test jacoco:report

      - name: Extract coverage from HTML report
        run: |
          FILE="target/site/jacoco/index.html"
          if [ -f "$FILE" ]; then
            # Pega a linha do <tfoot> que contém "Total"
            COVERAGE_LINE=$(grep -A 1 '<tfoot>' "$FILE" | grep 'Total')
            # Extrai o valor da primeira célula <td> com classe ctr2 (que é a cobertura correta)
            COVERAGE=$(echo "$COVERAGE_LINE" | grep -oP '(?<=<td class="ctr2">)[0-9]{1,3}%')
            # Pega só o primeiro resultado (caso tenha mais de um)
            COVERAGE=$(echo "$COVERAGE" | head -n 1)
            # Valor mínimo da cobertura (exemplo 80%)
            MIN_COVERAGE=80
            # Remove o % para comparar
            COVERAGE_VALUE=$(echo "$COVERAGE" | tr -d '%')
            
            echo "Cobertura mínima exigida: ${MIN_COVERAGE}%"
            echo "Cobertura atual: ${COVERAGE}"

            if [ "$COVERAGE_VALUE" -ge "$MIN_COVERAGE" ]; then
              echo "✅ Cobertura mínima atingida."
            else
              echo "❌ Cobertura abaixo do mínimo."
            fi

            echo "✅ Cobertura de instruções: $COVERAGE"
          else
            echo "❌ Arquivo de cobertura não encontrado: $FILE"
            exit 1
          fi

  create-pr-to-develop:
    needs: test-and-report
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set current branch name
        id: vars
        run: echo "branch_name=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT

      - name: Create pull request to develop
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: develop
          branch: ${{ steps.vars.outputs.branch_name }}
          title: "Auto PR: Merge '${{ steps.vars.outputs.branch_name }}' into develop"
          body: |
            Este PR foi criado automaticamente após o build e testes com Jacoco.
          draft: false
          labels: automated-pr
