name: Run Tests and Create PR

on:
  push:
    branches:
      - '**'  # Qualquer branch

jobs:
  test-and-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run tests and generate Jacoco report
        run: mvn clean test jacoco:report

      - name: Extract coverage from HTML report
        run: |
          FILE="target/site/jacoco/index.html"
          if [ -f "$FILE" ]; then
            # Extrai conteúdo entre <tfoot> e </tfoot>
            LINE=$(sed -n '/<tfoot>/,/<\/tfoot>/p' "$FILE" | grep '<td>Total</td>')
            if [ -z "$LINE" ]; then
              echo "❌ Linha com 'Total' não encontrada"
              exit 1
            fi

            # Extrai todas as tags <td> e pega a terceira
            tds=$(echo "$LINE" | grep -o '<td[^>]*>.*</td>')
            COVERAGE=$(echo "$tds" | sed -n '3p' | sed 's/<[^>]*>//g')

            if [ -z "$COVERAGE" ]; then
              echo "❌ Cobertura não encontrada"
              exit 1
            fi

            echo "✅ Cobertura total: $COVERAGE"
          else
            echo "❌ Arquivo de cobertura não encontrado: $FILE"
            exit 1
          fi

  create-pr-to-develop:
    needs: test-and-report
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create pull request to develop
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: develop
          branch: ${{ github.ref_name }}
          title: "Auto PR: Merge '${{ github.ref_name }}' into develop"
          body: |
            Este PR foi criado automaticamente após o build e testes com Jacoco.
          draft: false
          labels: automated-pr
