name: Run Unit Tests and Coverage, Auto PR to develop

on:
  push:
    branches:
      - '**'   # Qualquer branch

jobs:
  test-and-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run tests and generate coverage report
        run: |
          mvn clean test jacoco:report

      - name: Show coverage summary (from jacoco.xml)
        run: |
          COVERAGE_XML="validatejwt/target/site/jacoco/jacoco.xml"
          if [ -f "$COVERAGE_XML" ]; then
            echo "Coverage summary from jacoco.xml:"
            # Simples extração das linhas com cobertura usando xmllint e grep
            xmllint --xpath "//counter[@type='INSTRUCTION']" $COVERAGE_XML | \
              sed 's/></>\n</g' | grep -E 'missed|covered|covered="([0-9]+)"' || echo "Coverage data not found"
          else
            echo "Coverage XML not found!"
          fi

  create-pr-to-develop:
    needs: test-and-coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create PR to develop branch
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: develop
          branch: ${{ github.ref_name }}
          title: "Auto PR: Sync branch '${{ github.ref_name }}' to develop"
          body: |
            Este PR foi criado automaticamente para sincronizar as mudanças da branch `${{ github.ref_name }}` na `develop`.
          draft: false
          labels: automated-pr
